<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Geocoding.Core" Version="5.0.0" />
    <PackageReference Include="Geocoding.Google" Version="5.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="JSON\realestate.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
